# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/abner/Desktop/Operativos/Proyecto1/ProyectoIOperativos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/abner/Desktop/Operativos/Proyecto1/ProyectoIOperativos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abner/Desktop/Operativos/Proyecto1/ProyectoIOperativos/CMakeFiles /home/abner/Desktop/Operativos/Proyecto1/ProyectoIOperativos//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/abner/Desktop/Operativos/Proyecto1/ProyectoIOperativos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Creator

# Build rule for target.
Creator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Creator
.PHONY : Creator

# fast build rule for target.
Creator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Creator.dir/build.make CMakeFiles/Creator.dir/build
.PHONY : Creator/fast

#=============================================================================
# Target rules for targets named Client

# Build rule for target.
Client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Client
.PHONY : Client

# fast build rule for target.
Client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/build
.PHONY : Client/fast

#=============================================================================
# Target rules for targets named Reconstructor

# Build rule for target.
Reconstructor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Reconstructor
.PHONY : Reconstructor

# fast build rule for target.
Reconstructor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Reconstructor.dir/build.make CMakeFiles/Reconstructor.dir/build
.PHONY : Reconstructor/fast

#=============================================================================
# Target rules for targets named Statistics

# Build rule for target.
Statistics: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Statistics
.PHONY : Statistics

# fast build rule for target.
Statistics/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statistics.dir/build.make CMakeFiles/Statistics.dir/build
.PHONY : Statistics/fast

#=============================================================================
# Target rules for targets named headers

# Build rule for target.
headers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 headers
.PHONY : headers

# fast build rule for target.
headers/fast:
	$(MAKE) $(MAKESILENT) -f Libs/libFort/libfort-0.4.2/CMakeFiles/headers.dir/build.make Libs/libFort/libfort-0.4.2/CMakeFiles/headers.dir/build
.PHONY : headers/fast

#=============================================================================
# Target rules for targets named fort

# Build rule for target.
fort: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fort
.PHONY : fort

# fast build rule for target.
fort/fast:
	$(MAKE) $(MAKESILENT) -f Libs/libFort/libfort-0.4.2/lib/CMakeFiles/fort.dir/build.make Libs/libFort/libfort-0.4.2/lib/CMakeFiles/fort.dir/build
.PHONY : fort/fast

Client.o: Client.c.o
.PHONY : Client.o

# target to build an object file
Client.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/Client.c.o
.PHONY : Client.c.o

Client.i: Client.c.i
.PHONY : Client.i

# target to preprocess a source file
Client.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/Client.c.i
.PHONY : Client.c.i

Client.s: Client.c.s
.PHONY : Client.s

# target to generate assembly for a file
Client.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Client.dir/build.make CMakeFiles/Client.dir/Client.c.s
.PHONY : Client.c.s

Creator.o: Creator.c.o
.PHONY : Creator.o

# target to build an object file
Creator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Creator.dir/build.make CMakeFiles/Creator.dir/Creator.c.o
.PHONY : Creator.c.o

Creator.i: Creator.c.i
.PHONY : Creator.i

# target to preprocess a source file
Creator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Creator.dir/build.make CMakeFiles/Creator.dir/Creator.c.i
.PHONY : Creator.c.i

Creator.s: Creator.c.s
.PHONY : Creator.s

# target to generate assembly for a file
Creator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Creator.dir/build.make CMakeFiles/Creator.dir/Creator.c.s
.PHONY : Creator.c.s

Reconstructor.o: Reconstructor.c.o
.PHONY : Reconstructor.o

# target to build an object file
Reconstructor.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Reconstructor.dir/build.make CMakeFiles/Reconstructor.dir/Reconstructor.c.o
.PHONY : Reconstructor.c.o

Reconstructor.i: Reconstructor.c.i
.PHONY : Reconstructor.i

# target to preprocess a source file
Reconstructor.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Reconstructor.dir/build.make CMakeFiles/Reconstructor.dir/Reconstructor.c.i
.PHONY : Reconstructor.c.i

Reconstructor.s: Reconstructor.c.s
.PHONY : Reconstructor.s

# target to generate assembly for a file
Reconstructor.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Reconstructor.dir/build.make CMakeFiles/Reconstructor.dir/Reconstructor.c.s
.PHONY : Reconstructor.c.s

Statistics.o: Statistics.c.o
.PHONY : Statistics.o

# target to build an object file
Statistics.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statistics.dir/build.make CMakeFiles/Statistics.dir/Statistics.c.o
.PHONY : Statistics.c.o

Statistics.i: Statistics.c.i
.PHONY : Statistics.i

# target to preprocess a source file
Statistics.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statistics.dir/build.make CMakeFiles/Statistics.dir/Statistics.c.i
.PHONY : Statistics.c.i

Statistics.s: Statistics.c.s
.PHONY : Statistics.s

# target to generate assembly for a file
Statistics.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Statistics.dir/build.make CMakeFiles/Statistics.dir/Statistics.c.s
.PHONY : Statistics.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... headers"
	@echo "... Client"
	@echo "... Creator"
	@echo "... Reconstructor"
	@echo "... Statistics"
	@echo "... fort"
	@echo "... Client.o"
	@echo "... Client.i"
	@echo "... Client.s"
	@echo "... Creator.o"
	@echo "... Creator.i"
	@echo "... Creator.s"
	@echo "... Reconstructor.o"
	@echo "... Reconstructor.i"
	@echo "... Reconstructor.s"
	@echo "... Statistics.o"
	@echo "... Statistics.i"
	@echo "... Statistics.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

